//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issues_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int Number { get; set; }
        public string Summary { get; set; }
        public string Descripton { get; set; }
        public int PriorityId { get; set; }
        public int AssigneeId { get; set; }
        public int StateId { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }

        public Issue()
        {
            Number = 0;
            Summary = "";
            Descripton = "";
        }
    }
}
